import type { Metadata } from "next";
import NavBar from "@/components/navbar";
import CommonProvider from "@/app/context/CommonContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>){
    return (
        <html lang="en">
            <body>
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                </link>
            <div className="flex w-screen h-screen">
                {children}
            </div>
        </body>
    </html>
  );
}
